name: Build Executable
on: [push]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.1'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'windows'
          options: --onefile, --name "autogui", --windowed, 